const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const engine=require('../lib/engine');const {load}=require('../lib/knowledge');const {projectMarkdown,parseProjectMarkdown,importProjectMarkdown}=require('../lib/project-markdown');const {SessionStore}=require('../lib/session-store');
const root=path.join(__dirname,'..'),kb=load(root,{includeUnowned:true});
test('draft Markdown preserves requirements, exact abilities, identities, notes and locks',async()=>{
 let p=await engine.create(kb,{mode:'retheme',title:'Reusable test',mechanicalBrief:'Keep information reliable',essentialCharacters:['Yoda']},root,['empath','imp']);p=engine.mutate(kb,p,{type:'begin-retheme'},root);p=engine.mutate(kb,p,{type:'mapping',roleId:'empath',characterId:'yoda'},root);p=engine.mutate(kb,p,{type:'notes',roleId:'empath',notes:'Check this interaction',resolved:false},root);p=engine.mutate(kb,p,{type:'locks',roleId:'empath',botcRole:true,starWarsCharacter:true},root);
 const text=projectMarkdown(p);assert(text.includes('# Reusable test'));const data=parseProjectMarkdown(text,kb);const restored=await importProjectMarkdown(kb,data,root,engine);assert.equal(restored.title,p.title);assert.equal(restored.stage,'RETHEME');assert.equal(restored.request.mechanicalBrief,p.request.mechanicalBrief);assert.deepEqual(restored.entries.map(e=>[e.botcRole.id,e.ability,e.starWarsIdentity,e.notes,e.reviewResolved,e.locks]),p.entries.map(e=>[e.botcRole.id,e.ability,e.starWarsIdentity,e.notes,e.reviewResolved,e.locks]));
});
test('Markdown validation rejects unavailable roles and ability edits',async()=>{const p=await engine.create(kb,{mode:'retheme'},root,['empath','imp']);const text=projectMarkdown(p);assert.throws(()=>parseProjectMarkdown(text.replace('"id": "empath"','"id": "missing"'),kb),/unavailable/);assert.throws(()=>parseProjectMarkdown(text.replace(JSON.stringify(p.entries[0].ability),JSON.stringify('Invented ability')),kb),/differs/);});
test('desktop sessions retain undo only for the current script and list no past projects',()=>{const store=new SessionStore();let p=store.save({id:'a',title:'A',state:'DRAFT'},'new');p=store.save({...p,title:'B'},'rename',p.version);assert.equal(store.move('a',-1,p.version).title,'A');store.save({id:'b',title:'Fresh',state:'DRAFT'},'new');assert.deepEqual(store.list(),[]);assert.throws(()=>store.current('a'));assert.throws(()=>new SessionStore().current('b'));});
