const fs=require('node:fs'),path=require('node:path');
const {load}=require('../lib/knowledge');
const root=path.join(__dirname,'..'),out=path.join(root,'dist','web');
fs.mkdirSync(out,{recursive:true});
const kb=load(root,{includeUnowned:true});
kb.settings={ownedEditions:kb.botcEditions.map(e=>e.id)};
if(kb.errors.length)throw Error('Fix corpus errors before building the website.');
fs.writeFileSync(path.join(out,'corpus.json'),JSON.stringify(kb));
for(const file of ['app.js','styles.css','connections.js'])fs.copyFileSync(path.join(root,'public',file),path.join(out,file));
let html=fs.readFileSync(path.join(root,'public','index.html'),'utf8');
html=html.replace('<script src="/app.js">','<script src="./static.js"></script><script src="./app.js">').replace('href="/styles.css"','href="./styles.css"').replace('src="/connections.js"','src="./connections.js"');
html=html.replace('Build or import your BOTC mechanics first. Confirm the script, then choose a Star Wars character for each role.','One-off builder: design or import BOTC mechanics, then choose your cast. Export TXT before closing the page and import it next time. Nothing is saved online.');
fs.writeFileSync(path.join(out,'index.html'),html);
const modules=['settings','knowledge','engine','export','script-text','project-markdown'].map(name=>JSON.stringify('./'+name)+':function(require,module,exports){\n'+fs.readFileSync(path.join(root,'lib',name+'.js'),'utf8')+'\n}');
const criteria=fs.readFileSync(path.join(root,'data','design-criteria.json'),'utf8');
const prelude=`'use strict';\n(()=>{const modules={${modules.join(',')}};const cache={};const criteria=${JSON.stringify(criteria)};function require(id){if(id==='node:fs')return {readFileSync:()=>criteria};if(id==='node:path')return {join:(...parts)=>parts.join('/')};if(id==='node:crypto')return {randomUUID:()=>crypto.randomUUID()};if(id==='./model')return {ask:async()=>null};if(id==='./laya')return {available:()=>false,choose:async()=>null,progress:()=>{}};if(cache[id])return cache[id].exports;if(!modules[id])throw Error('Unknown module '+id);const module={exports:{}};cache[id]=module;modules[id](require,module,module.exports);return module.exports;}\n`;
fs.writeFileSync(path.join(out,'static.js'),prelude+fs.readFileSync(path.join(root,'public','static-adapter.js'),'utf8')+'\n})();');
fs.writeFileSync(path.join(out,'.nojekyll'),'');
console.log('Static website built: '+out);
